// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXJNLwOF5hcDTK8IWczHuOtZcoj786d-8',
    appId: '1:214152575355:web:f52136a3f38f01a7c4e5de',
    messagingSenderId: '214152575355',
    projectId: 'flutterauth-213b5',
    authDomain: 'flutterauth-213b5.firebaseapp.com',
    storageBucket: 'flutterauth-213b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1UnwMGCRAt9pRhKGsF1B7mmkM6k3xbOA',
    appId: '1:214152575355:android:8a963527ad5f33b9c4e5de',
    messagingSenderId: '214152575355',
    projectId: 'flutterauth-213b5',
    storageBucket: 'flutterauth-213b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr5DEm2sCI6LurkWf5JqcoyXm1Qwo-LXU',
    appId: '1:214152575355:ios:1d73bbb9650c1b37c4e5de',
    messagingSenderId: '214152575355',
    projectId: 'flutterauth-213b5',
    storageBucket: 'flutterauth-213b5.appspot.com',
    iosBundleId: 'com.example.flutterall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr5DEm2sCI6LurkWf5JqcoyXm1Qwo-LXU',
    appId: '1:214152575355:ios:0c6846c1b0cad384c4e5de',
    messagingSenderId: '214152575355',
    projectId: 'flutterauth-213b5',
    storageBucket: 'flutterauth-213b5.appspot.com',
    iosBundleId: 'com.example.flutterall.RunnerTests',
  );
}
